### ISSUE TITLE
TOPAS optional

### ISSUE THREAD

**Issue by ferdymercury** [topasmc/dicom-interface#11]
In https://github.com/topasmc/dicom-interface/blob/master/README.md it says TOPAS is mandatory, but I think the library can be used also outside TOPAS, for example with gpmc. Maybe you can change it to 'optional' in the README under the requirements section?

**Comment by jungwookshin** [comment]
Yes, it's optional (I will do). But I would like mention this doesn't limit MC engine but we have tested only with TOPAS.
