### ISSUE TITLE
Make GPU code more abstract

### ISSUE THREAD

**Issue by ferdymercury** [topasmc/dicom-interface#12]
One potential enhancement could be to make the parallel code more abstract, so that it can run both on OpenCL and CUDA.

This could be a very clean approach that does not need CUDA-specific hand-coding:
https://www.khronos.org/sycl/

**Comment by jungwookshin** [comment]
Thank you for update on SYCL. When Dave and I looked its potential a year ago (or ealier), it was not easy to find example code that we could test whether it's suitable for our needs or not. It looks promising and has lot more example codes now. Right now we haven come too far with CUDA.
