### ISSUE TITLE
Missing tutorial

### ISSUE THREAD

**Issue by ferdymercury** [topasmc/dicom-interface#15]
In the Readme, a file is mentioned that does not exist in the repo:
`topas beam_view.txt`

**Comment by jungwookshin** [comment]
I have added visualization files for beam, QA, and plan in the topas/tutorial directory. 
They are beam_view.txt, QA_view.txt, and plan_hu_view.txt. Note that the parameters in those files are same but the only difference is what to include, i.e., "includeFile = QA.txt" for water phantom visualization, "includeFile=plan_hu.txt" is DICOM images, respectively. 
also the README and wiki pages are updated accordingly. Thank you for reporting!

**Comment by ferdymercury** [comment]
Thanks!!
