### ISSUE TITLE
rect3d bug

### ISSUE THREAD

**Issue by ferdymercury** [topasmc/dicom-interface#7]
I think when one calls

`x = new int[N]`

then in the destructor it should say
`delete[] x;`
with the square brackets.

See http://www.cplusplus.com/reference/new/operator%20delete[]/

**Comment by ferdymercury** [comment]
See also http://www.cplusplus.com/forum/general/36130/

**Comment by jungwookshin** [comment]
Thanks! Yes, memory of array should be released in with the square brackets!
